import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/components/theme-provider";

import "./globals.css";

const poppins = Poppins({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"], // Adjust weights as needed
  display: "swap",
});

export const metadata: Metadata = {
  manifest: "/manifest.json",
  title: "Ishwardi transport and agency",
  description: "Generated by Ishwardi transport and agency",
  icons: {
    icon: "/web-app-manifest-small.png",
    shortcut: "/web-app-manifest-small.png",
    apple: "/web-app-manifest-small.png",
  },
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "Ishwardi transport and agency",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${poppins.variable} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <main>
            {children}
            <Toaster richColors closeButton />
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
